# name of the workflow.
# this is optional.
name: Deploy

# events that will trigger this workflow.
# here, we only have "pull_request", so the workflow will run
# whenever we create a pull request.
# other examples: [push] and [pull_request, push]
on: [push]

# each workflow must have at least one job.
# jobs run in parallel by default (we can change that).
# each job groups together a series of steps to accomplish a purpose.
jobs:
  # name of the job
  deploy:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1



      - name: package
        run: zip artifact.zip main.py
      
      - name: push to s3
        run: aws s3 cp artifact.zip s3://terraform-20230324040435789100000001/artifact.zip
