# name of the workflow.
# this is optional.
name: Continuous Integration

# events that will trigger this workflow.
# here, we only have "pull_request", so the workflow will run
# whenever we create a pull request.
# other examples: [push] and [pull_request, push]
on: [pull_request]

# each workflow must have at least one job.
# jobs run in parallel by default (we can change that).
# each job groups together a series of steps to accomplish a purpose.
jobs:
  # name of the job
  first:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install pytest

      - name: test
        run: python -m pytest -v

  lint:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install pylint
        run: pip install pylint

      - name: test
        run: python -m pylint main.py